version: "3.0"
services:
    nginx:
        container_name: nginx
        image: nginx:1.15.12-alpine
        ports:
            - 80:80
        volumes:
            - ./html:/usr/share/nginx/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    node:
        container_name: nodejs
        image: node:12.18.3-alpine
        ports:
            - 5000:5000
        volumes:
            - ./server:/app
        command: node /app/server.js
